### ISSUE TITLE
Prepare shift from XhrIo?

### ISSUE THREAD

**Issue by Frozenlock** [Day8/re-frame-http-fx#21]
As commented on #18, the next version of cljs-ajax is supposed to drop XhrIo.

>It is intended that the default implementation for JavaScript uses XmlHttpRequest directly and XhrIO is deprecated in 0.8. Be warned.

Is this effect handler going to be updated to use the different backend, or will it drop cljs-ajax?

**Comment by hipitihop** [comment]
Apologies for being so tardy tending to issues and pr's. I haven't reviewed implications or made any decisions yet regarding the backend and dependence on cljs-ajax and in turn XhrIo. I thinking any consideration for moving away should include looking at Fetch to see if it offers anything https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
Comments & suggestions welcomed

**Comment by dgroulx** [comment]
An upvote for at the very least letting the user override the default :api key.

**Comment by mike-thompson-day8** [comment]
I'm closing this (as part of some spring cleaning) 

This issue was opened in 2017, and the move away from XhrIO has never happened.  Neither do I suspect it will ever happen.  

@dgroulx  I can't parse your comment about overriding `:api` - there's insufficient detail given  - and it seems to be a feature request and unrelated to moving away from XhrIO. Please open a separate issue describing the problem in more detail.
