### ISSUE TITLE
Version v0.2.0 release

### ISSUE THREAD

**Issue by mrrodriguez** [day8/re-frame-http-fx#40]
I noticed that the latest released version is  "v0.2.0".

The odd part to this is the prefix "v" in the version string. No previous version had this prefix, eg. "0.1.6".

Was this prefix added intentionally? I wasn't sure if it will cause any issue in typical semantic versioning systems or lexicographical comparisons, etc.

**Comment by Wegi** [comment]
I wanted to add, that version-checkers like depot.outdated or ancient fail because they think 0.1.6 is newer. :)

**Comment by superstructor** [comment]
This was a mistake in the `v0.2.0` deployment with the combination of the `day8/lein-git-inject` version and configuration that was used at the time.

Have fixed with release of `0.2.1`. Obviously, unfortunately so that we don't break anyone's builds `v0.2.0` will have to stay indefinitely. The good news is in my testing the sort order is still correct and `0.2.1` is listed as the newest release.
